/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CustomerrService } from "../customerr.service";
import { CustomerrCreateInput } from "./CustomerrCreateInput";
import { Customerr } from "./Customerr";
import { CustomerrFindManyArgs } from "./CustomerrFindManyArgs";
import { CustomerrWhereUniqueInput } from "./CustomerrWhereUniqueInput";
import { CustomerrUpdateInput } from "./CustomerrUpdateInput";

export class CustomerrControllerBase {
  constructor(protected readonly service: CustomerrService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Customerr })
  async createCustomerr(
    @common.Body() data: CustomerrCreateInput
  ): Promise<Customerr> {
    return await this.service.createCustomerr({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Customerr] })
  @ApiNestedQuery(CustomerrFindManyArgs)
  async customerrs(@common.Req() request: Request): Promise<Customerr[]> {
    const args = plainToClass(CustomerrFindManyArgs, request.query);
    return this.service.customerrs({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Customerr })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async customerr(
    @common.Param() params: CustomerrWhereUniqueInput
  ): Promise<Customerr | null> {
    const result = await this.service.customerr({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Customerr })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCustomerr(
    @common.Param() params: CustomerrWhereUniqueInput,
    @common.Body() data: CustomerrUpdateInput
  ): Promise<Customerr | null> {
    try {
      return await this.service.updateCustomerr({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Customerr })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCustomerr(
    @common.Param() params: CustomerrWhereUniqueInput
  ): Promise<Customerr | null> {
    try {
      return await this.service.deleteCustomerr({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
