/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Customerr as PrismaCustomerr } from "@prisma/client";

export class CustomerrServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CustomerrCountArgs, "select">
  ): Promise<number> {
    return this.prisma.customerr.count(args);
  }

  async customerrs(
    args: Prisma.CustomerrFindManyArgs
  ): Promise<PrismaCustomerr[]> {
    return this.prisma.customerr.findMany(args);
  }
  async customerr(
    args: Prisma.CustomerrFindUniqueArgs
  ): Promise<PrismaCustomerr | null> {
    return this.prisma.customerr.findUnique(args);
  }
  async createCustomerr(
    args: Prisma.CustomerrCreateArgs
  ): Promise<PrismaCustomerr> {
    return this.prisma.customerr.create(args);
  }
  async updateCustomerr(
    args: Prisma.CustomerrUpdateArgs
  ): Promise<PrismaCustomerr> {
    return this.prisma.customerr.update(args);
  }
  async deleteCustomerr(
    args: Prisma.CustomerrDeleteArgs
  ): Promise<PrismaCustomerr> {
    return this.prisma.customerr.delete(args);
  }
}
