/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Customerr } from "./Customerr";
import { CustomerrCountArgs } from "./CustomerrCountArgs";
import { CustomerrFindManyArgs } from "./CustomerrFindManyArgs";
import { CustomerrFindUniqueArgs } from "./CustomerrFindUniqueArgs";
import { CreateCustomerrArgs } from "./CreateCustomerrArgs";
import { UpdateCustomerrArgs } from "./UpdateCustomerrArgs";
import { DeleteCustomerrArgs } from "./DeleteCustomerrArgs";
import { CustomerrService } from "../customerr.service";
@graphql.Resolver(() => Customerr)
export class CustomerrResolverBase {
  constructor(protected readonly service: CustomerrService) {}

  async _customerrsMeta(
    @graphql.Args() args: CustomerrCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Customerr])
  async customerrs(
    @graphql.Args() args: CustomerrFindManyArgs
  ): Promise<Customerr[]> {
    return this.service.customerrs(args);
  }

  @graphql.Query(() => Customerr, { nullable: true })
  async customerr(
    @graphql.Args() args: CustomerrFindUniqueArgs
  ): Promise<Customerr | null> {
    const result = await this.service.customerr(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Customerr)
  async createCustomerr(
    @graphql.Args() args: CreateCustomerrArgs
  ): Promise<Customerr> {
    return await this.service.createCustomerr({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Customerr)
  async updateCustomerr(
    @graphql.Args() args: UpdateCustomerrArgs
  ): Promise<Customerr | null> {
    try {
      return await this.service.updateCustomerr({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Customerr)
  async deleteCustomerr(
    @graphql.Args() args: DeleteCustomerrArgs
  ): Promise<Customerr | null> {
    try {
      return await this.service.deleteCustomerr(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
